/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f407xx.h"
#include "reg_util.h"
#include "bsp_lcd.h"
#include "cmsis_gcc.h"
#include "../lvgl/lvgl.h"
#include "../lv_conf.h"

#define RGB888(r,g,b)  (((r) << 16) | ((g) << 8) | (b))

#define VIOLET   	RGB888(148,0,211)
#define INDIGO   	RGB888(75,0,130)
#define BLUE   		RGB888(0,0,255)
#define GREEN   	RGB888(0,255,0)
#define YELLOW   	RGB888(255,255,0)
#define ORANGE   	RGB888(255,127,0)
#define RED   		RGB888(255,0,0)
#define WHITE   	RGB888(255,255,255)
#define BLACK		RGB888(0,0,0)






void SystemClockSetup(void);
void SysTickSetup(void);
void BlueLEDSetup(void);

static void SetSystemClockTo16Mhz(void);

static void delay_50ms(void){
	for(uint32_t i = 0 ; i<(0xFFFFU * 10U);i++);
}

static volatile bool tick_led_on = 0;

/*Screen  Defines*/
#define TFT_HOR_RES 240
#define TFT_VER_RES 320

#define TFT_EXT_FB		0		/*Frame buffer is located into an external SDRAM*/
#define TFT_USE_GPU		0		/*Enable hardware accelerator*/

void screen_init(void);
void lcd_flush_cb(lv_display_t * disp, const lv_area_t * area, uint8_t * px_map);

static volatile uint32_t t_saved = 0;
/*End Screen Defines*/




int main(void)
{
	SystemClockSetup();
	//SetSystemClockTo16Mhz();
	bsp_lcd_init();
	bsp_lcd_set_orientation(LANDSCAPE);
	bsp_lcd_set_background_color(WHITE);

	bsp_lcd_fill_rect(VIOLET, 0, 320, 0, 34);
	bsp_lcd_fill_rect(INDIGO, 0, 320, (34 *1), 34);
	bsp_lcd_fill_rect(BLUE, 0, 320, (34*2), 34);
	bsp_lcd_fill_rect(GREEN, 0, 320, (34*3), 34);
	bsp_lcd_fill_rect(YELLOW, 0, 320, (34*4), 34);
	bsp_lcd_fill_rect(ORANGE, 0, 320, (34*5), 34);
	bsp_lcd_fill_rect(RED, 0, 320, (34*6), 34);

	//ADD windowinng
	bsp_lcd_set_background_color(YELLOW);
	bsp_lcd_fill_rect(RED, 60, 200, 40, 160);


	// ADD smart windowing
	bsp_lcd_set_background_color(YELLOW);
	bsp_lcd_set_display_area(60,  259, 100, 139);
	bsp_lcd_send_cmd_mem_write();
	//make a small display buffer
	uint16_t data[200UL * 40UL];
	for(uint32_t i = 0; i < (200UL * 40UL); i++){
		data[i] = bsp_lcd_convert_rgb888_to_rgb565(RED);
	}
	bsp_lcd_write((uint8_t*)data, (200UL * 40UL));


	bsp_lcd_set_background_color(BLACK);


	__enable_irq();
	BlueLEDSetup();
	SysTickSetup();

	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();
	delay_50ms();



	/* We have a screen above and we can baremetal control it
	 * Onwards now we will use LVGL to talk to the screen so lets
	 * set that up and see how it works
	 */

	screen_init();




	// change the active screens background color
	lv_obj_set_style_bg_color(lv_screen_active(), lv_color_hex(0x003a57), LV_PART_MAIN);
	lv_obj_set_style_text_color(lv_screen_active(), lv_color_hex(0xffffff), LV_PART_MAIN);



	lv_obj_t *mbox1 = lv_msgbox_create(NULL);

	lv_msgbox_add_title(mbox1, "Hello");

	lv_msgbox_add_text(mbox1, "This is a message box with two buttons.");
	lv_msgbox_add_close_button(mbox1);

	lv_obj_t *btn;
	btn = lv_msgbox_add_footer_button(mbox1, "Apply");
	btn = lv_msgbox_add_footer_button(mbox1, "Cancel");



	// lets make a spinner
	lv_obj_t * spinner = lv_spinner_create(lv_screen_active());
	lv_obj_set_size(spinner, 64, 64);
	lv_obj_align(spinner, LV_ALIGN_BOTTOM_MID, 0, 0);



	/*End LVGL*/



    /* Application Super loop */
	while(1){

		lv_timer_handler();
		//let lvgl handle any tasks it needs
		delay_50ms();
	}
}



/*Function to initialize the screen as a LVGL element*/
void screen_init(void){
	lv_color_t *draw_buf1;
	lv_color_t *draw_buf2;

	bsp_lcd_init();

	draw_buf1 = (lv_color_t*)bsp_lcd_get_draw_buffer1_addr();
	draw_buf2 = (lv_color_t*)bsp_lcd_get_draw_buffer2_addr();

	//Init LVGL
	lv_init();

	//Init LVGL with our screen size
	lv_display_t * disp = lv_display_create(BSP_LCD_ACTIVE_HEIGHT, BSP_LCD_ACTIVE_WIDTH);

	//Initialize and set a buffer
	lv_display_set_buffers(disp, draw_buf1, draw_buf2, ((10UL * 1024UL) / 2), LV_DISPLAY_RENDER_MODE_PARTIAL);

	//Set a flush callback so lvgl can draw to our screen
	lv_display_set_flush_cb(disp, lcd_flush_cb);

	lv_display_set_rotation(disp, LV_DISPLAY_ROTATION_90);

	lv_display_set_color_format(disp, LV_COLOR_FORMAT_RGB565);





}


/*
 * Callback used by LVGL to render to the Screen
 */
void lcd_flush_cb(lv_display_t * disp, const lv_area_t * area, uint8_t * px_map){

	uint16_t * color_p = (uint16_t *)px_map;

	if(area->x2 < 0 || area->y2 < 0 || area->x1 > (TFT_HOR_RES - 1) || area->y1 > (TFT_VER_RES - 1)) {
		lv_display_flush_ready(disp);
		return;
	}

	/*Return if the area is out the screen*/
	if (area->x2 < 0)
		return;
	if (area->y2 < 0)
		return;
	if (area->x1 > TFT_HOR_RES - 1)
		return;
	if (area->y1 > TFT_VER_RES - 1)
		return;

	/*Truncate the area to the screen*/
	int32_t act_x1 = area->x1 < 0 ? 0 : area->x1;
	int32_t act_y1 = area->y1 < 0 ? 0 : area->y1;
	int32_t act_x2 = area->x2 > TFT_HOR_RES - 1 ? TFT_HOR_RES - 1 : area->x2;
	int32_t act_y2 = area->y2 > TFT_VER_RES - 1 ? TFT_VER_RES - 1 : area->y2;

    lv_coord_t w = (area->x2 - area->x1) + 1;


	//set the drawing region
    bsp_lcd_set_display_area(act_x1,act_x2,act_y1,act_y2);
    uint32_t len = (act_x2 - act_x1 + 1) * 2ul;

	bsp_lcd_send_cmd_mem_write();
	for(uint32_t y = act_y1; y <= act_y2; y++){
		bsp_lcd_write((uint8_t*)color_p, len);

		color_p += w;
	}

	delay_50ms();

	//Tell LVGL we are ready to flush
	//bsp_lcd_flush();
	lv_display_flush_ready(disp);
}



void BlueLEDSetup(void){

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |= GPIO_MODER_MODER15_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER15_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_15;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR15_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_1;

	GPIOD->BSRR |= GPIO_BSRR_BS_15;
}

void SysTickSetup(void){
	uint32_t ticks = 168000 - 1;

	SysTick->LOAD = (uint32_t) ticks;
	NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);
	SysTick->VAL = 0UL;

	SysTick->CTRL  = SysTick_CTRL_CLKSOURCE_Msk |
	                   SysTick_CTRL_TICKINT_Msk   |
	                   SysTick_CTRL_ENABLE_Msk;

}

void SysTick_Handler(void) {
	/*flip our LED/ Data signal In case we need an indicator
	tick_led_on = !tick_led_on;

	if (tick_led_on) {
		GPIOD->BSRR |= GPIO_BSRR_BS_15;
	} else {
		GPIOD->BSRR |= GPIO_BSRR_BR_15;
	}*/

	// report elapsed time to lvgl
	lv_tick_inc(1);


}



void SystemClockSetup(void){
	RCC_TypeDef *pRcc = RCC;
	FLASH_TypeDef *pFlash = FLASH;
	PWR_TypeDef *pPwr = PWR;



	// program flash overdrive and wait states
	REG_SET_VAL(pFlash->ACR, 0x5U, 0xFU, FLASH_ACR_LATENCY_Pos);

	//2. Over drive settings
	REG_SET_BIT(pRcc->APB1ENR, RCC_APB1ENR_PWREN_Pos); /*Enable clock for PWR register access*/
	REG_SET_BIT(pPwr->CR, PWR_CR_VOS_Pos); 				/*VOS = 1*/


	// set up main PLL
	REG_SET_VAL(pRcc->PLLCFGR, 0x8U, 0x3FU, RCC_PLLCFGR_PLLM_Pos); //PLL_M
	REG_SET_VAL(pRcc->PLLCFGR, 168U, 0x1FFU, RCC_PLLCFGR_PLLN_Pos); //PLL_N
	REG_SET_VAL(pRcc->PLLCFGR, 0x00U, 0x3U, RCC_PLLCFGR_PLLP_Pos); //PLL_P

	// clock prescalers
	REG_SET_VAL(pRcc->CFGR, 0U, 0xFU, RCC_CFGR_HPRE_Pos); /*AHB prescaler*/
	REG_SET_VAL(pRcc->CFGR, 0x5U, 0x7U, RCC_CFGR_PPRE1_Pos); /*APB1 prescaler*/
	REG_SET_VAL(pRcc->CFGR, 0x4U, 0x7U, RCC_CFGR_PPRE2_Pos); /*APB2 prescaler*/

	//Turn On PLL and wait for PLL READY
	REG_SET_BIT(pRcc->CR, RCC_CR_PLLON_Pos);
	while(!REG_READ_BIT(pRcc->CR, RCC_CR_PLLRDY_Pos));

	//use PLL as system clock
	REG_SET_VAL(pRcc->CFGR, 0x2U, 0x3U, RCC_CFGR_SW_Pos);
	while(!(REG_READ_VAL(pRcc->CFGR, 0x3U, RCC_CFGR_SWS_Pos) == 0x2U));

}

/*
 * Function to set system clock to 16MHz
 */
static void SetSystemClockTo16Mhz(void) {

	// check if HSI is ready
	if((RCC->CR & RCC_CR_HSIRDY) == 0){
		//set HSI as clock
		RCC->CR |= RCC_CR_HSION;

		//wait until system clock swaps
		while((RCC->CR & RCC_CR_HSIRDY) == 0);

	}

	//set AHB prescaler to 1
	RCC->CFGR  |= RCC_CFGR_HPRE_DIV1;

	//APB1 prescaler
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV1;

	//APB2 Prescaler
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

	//select HSI as system clock
	RCC->CFGR &= (uint32_t)(uint32_t)~(RCC_CFGR_SW);
	RCC->CFGR |= RCC_CFGR_SW_HSI;

	/* Configure Flash prefetch, Instruction cache, Data cache and wait state */
	FLASH->ACR = FLASH_ACR_ICEN |FLASH_ACR_DCEN |FLASH_ACR_LATENCY_3WS;


	/* Disabling HSE Clock*/
	RCC->CR &= ~RCC_CR_HSEON;



}

